Started logging messages at Tue Mar 28 06:24:19 2017
Info:    Using UV tolerance 1e-006
Info:    Using UV tolerance 1e-006
Info:    HwNlibToTSLib options selected:
Info:        Points: Off
Info:        Curves: On
Info:        Surfaces: Off
Info:        BReps: On
Info:        Do not create IwAssembly/IwAssemblyInstance objects
Info:        Making untrimmed surfaces into BReps
Info:        Making solids into single BReps
Info:        Make components of failed trims
Info:        Make faces of failed B-reps
Info:    HW SAT v1.2.6-maint
Info:    Reading 
Info:    Processing 
Info:    Transferring 
Info:    
Info:    Found 0 points in file
Info:    Found 0 curves in file
Info:    Found 0 surfaces in file
Info:    Found 0 trimmed surfaces in file
Info:    Found 1 B-reps in file
Info:    Found 500 B-rep faces in file
Info:    
Info:    Using 3D tolerance 1e-006
Info:    Working on 0
Info:        Working on 60
Info:            Created 
Info:        Working on 61
Info:            Created 
Info:        Working on 84
Info:            Created 
Info:        Working on 88
Info:            Created 
Info:        Working on 6
Info:            Created 
Info:        Working on 83
Info:            Created 
Info:        Working on 119
Info:            Created 
Info:        Working on 154
Info:            Created 
Info:        Working on 191
Info:            Created 
Info:        Working on 190
Info:            Created 
Info:        Working on 148
Info:            Created 
Info:        Working on 9
Info:            Created 
Info:        Working on 147
Info:            Created 
Info:        Working on 13
Info:            Created 
Info:        Working on 189
Info:            Created 
Info:        Working on 21
Info:            Created 
Info:        Working on 240
Info:            Created 
Info:        Working on 38
Info:            Created 
Info:        Working on 241
Info:            Created 
Info:        Working on 64
Info:            Created 
Info:        Working on 194
Info:            Created 
Info:        Working on 97
Info:            Created 
Info:        Working on 126
Info:            Created 
Info:        Working on 136
Info:            Created 
Info:        Working on 125
Info:            Created 
Info:        Working on 231
Info:            Created 
Info:        Working on 287
Info:            Created 
Info:        Working on 411
Info:            Created 
Info:        Working on 561
Info:            Created 
Info:        Working on 162
Info:            Created 
Info:        Working on 230
Info:            Created 
Info:        Working on 405
Info:            Created 
Info:        Working on 573
Info:            Created 
Info:        Working on 792
Info:            Created 
Info:        Working on 796
Info:            Created 
Info:        Working on 578
Info:            Created 
Info:        Working on 197
Info:            Created 
Info:        Working on 1061
Info:            Created 
Info:        Working on 244
Info:            Created 
Info:        Working on 1375
Info:            Created 
Info:        Working on 325
Info:            Created 
Info:        Working on 1376
Info:            Created 
Info:        Working on 461
Info:            Created 
Info:        Working on 1064
Info:            Created 
Info:        Working on 658
Info:            Created 
Info:        Working on 563
Info:            Created 
Info:        Working on 794
Info:            Created 
Info:        Working on 291
Info:            Created 
Info:        Working on 397
Info:            Created 
Info:        Working on 559
Info:            Created 
Info:        Working on 280
Info:            Created 
Info:        Working on 370
Info:            Created 
Info:        Working on 551
Info:            Created 
Info:        Working on 759
Info:            Created 
Info:        Working on 531
Info:            Created 
Info:        Working on 279
Info:            Created 
Info:        Working on 544
Info:            Created 
Info:        Working on 771
Info:            Created 
Info:        Working on 1051
Info:            Created 
Info:        Working on 1055
Info:            Created 
Info:        Working on 778
Info:            Created 
Info:        Working on 386
Info:            Created 
Info:        Working on 1367
Info:            Created 
Info:        Working on 553
Info:            Created 
Info:        Working on 1711
Info:            Created 
Info:        Working on 780
Info:            Created 
Info:        Working on 1712
Info:            Created 
Info:        Working on 1057
Info:            Created 
Info:        Working on 1370
Info:            Created 
Info:        Working on 1372
Info:            Created 
Info:        Working on 761
Info:            Created 
Info:        Working on 1053
Info:            Created 
Info:        Working on 374
Info:            Created 
Info:        Working on 536
Info:            Created 
Info:        Working on 757
Info:            Created 
Info:        Working on 362
Info:            Created 
Info:        Working on 507
Info:            Created 
Info:        Working on 748
Info:            Created 
Info:        Working on 1014
Info:            Created 
Info:        Working on 728
Info:            Created 
Info:        Working on 361
Info:            Created 
Info:        Working on 741
Info:            Created 
Info:        Working on 1026
Info:            Created 
Info:        Working on 1356
Info:            Created 
Info:        Working on 1360
Info:            Created 
Info:        Working on 1033
Info:            Created 
Info:        Working on 523
Info:            Created 
Info:        Working on 1703
Info:            Created 
Info:        Working on 750
Info:            Created 
Info:        Working on 2049
Info:            Created 
Info:        Working on 1035
Info:            Created 
Info:        Working on 2050
Info:            Created 
Info:        Working on 1362
Info:            Created 
Info:        Working on 1706
Info:            Created 
Info:        Working on 1708
Info:            Created 
Info:        Working on 1016
Info:            Created 
Info:        Working on 1358
Info:            Created 
Info:        Working on 511
Info:            Created 
Info:        Working on 733
Info:            Created 
Info:        Working on 1012
Info:            Created 
Info:        Working on 499
Info:            Created 
Info:        Working on 704
Info:            Created 
Info:        Working on 1003
Info:            Created 
Info:        Working on 1319
Info:            Created 
Info:        Working on 983
Info:            Created 
Info:        Working on 498
Info:            Created 
Info:        Working on 996
Info:            Created 
Info:        Working on 1331
Info:            Created 
Info:        Working on 1692
Info:            Created 
Info:        Working on 1696
Info:            Created 
Info:        Working on 1338
Info:            Created 
Info:        Working on 720
Info:            Created 
Info:        Working on 2041
Info:            Created 
Info:        Working on 1005
Info:            Created 
Info:        Working on 2370
Info:            Created 
Info:        Working on 1340
Info:            Created 
Info:        Working on 2371
Info:            Created 
Info:        Working on 1698
Info:            Created 
Info:        Working on 2044
Info:            Created 
Info:        Working on 2046
Info:            Created 
Info:        Working on 1321
Info:            Created 
Info:        Working on 1694
Info:            Created 
Info:        Working on 708
Info:            Created 
Info:        Working on 988
Info:            Created 
Info:        Working on 1317
Info:            Created 
Info:        Working on 696
Info:            Created 
Info:        Working on 959
Info:            Created 
Info:        Working on 1308
Info:            Created 
Info:        Working on 1655
Info:            Created 
Info:        Working on 1288
Info:            Created 
Info:        Working on 695
Info:            Created 
Info:        Working on 1301
Info:            Created 
Info:        Working on 1667
Info:            Created 
Info:        Working on 2030
Info:            Created 
Info:        Working on 2034
Info:            Created 
Info:        Working on 1674
Info:            Created 
Info:        Working on 975
Info:            Created 
Info:        Working on 2362
Info:            Created 
Info:        Working on 1310
Info:            Created 
Info:        Working on 2683
Info:            Created 
Info:        Working on 1676
Info:            Created 
Info:        Working on 2684
Info:            Created 
Info:        Working on 2036
Info:            Created 
Info:        Working on 2365
Info:            Created 
Info:        Working on 2367
Info:            Created 
Info:        Working on 1657
Info:            Created 
Info:        Working on 2032
Info:            Created 
Info:        Working on 963
Info:            Created 
Info:        Working on 1293
Info:            Created 
Info:        Working on 1653
Info:            Created 
Info:        Working on 951
Info:            Created 
Info:        Working on 1264
Info:            Created 
Info:        Working on 1644
Info:            Created 
Info:        Working on 1993
Info:            Created 
Info:        Working on 1624
Info:            Created 
Info:        Working on 950
Info:            Created 
Info:        Working on 1637
Info:            Created 
Info:        Working on 2005
Info:            Created 
Info:        Working on 2351
Info:            Created 
Info:        Working on 2355
Info:            Created 
Info:        Working on 2012
Info:            Created 
Info:        Working on 1280
Info:            Created 
Info:        Working on 2675
Info:            Created 
Info:        Working on 1646
Info:            Created 
Info:        Working on 2995
Info:            Created 
Info:        Working on 2014
Info:            Created 
Info:        Working on 2996
Info:            Created 
Info:        Working on 2357
Info:            Created 
Info:        Working on 2678
Info:            Created 
Info:        Working on 2680
Info:            Created 
Info:        Working on 1995
Info:            Created 
Info:        Working on 2353
Info:            Created 
Info:        Working on 1268
Info:            Created 
Info:        Working on 1629
Info:            Created 
Info:        Working on 1991
Info:            Created 
Info:        Working on 1256
Info:            Created 
Info:        Working on 1600
Info:            Created 
Info:        Working on 1982
Info:            Created 
Info:        Working on 2314
Info:            Created 
Info:        Working on 1962
Info:            Created 
Info:        Working on 1255
Info:            Created 
Info:        Working on 1975
Info:            Created 
Info:        Working on 2326
Info:            Created 
Info:        Working on 2664
Info:            Created 
Info:        Working on 2668
Info:            Created 
Info:        Working on 2333
Info:            Created 
Info:        Working on 1616
Info:            Created 
Info:        Working on 2987
Info:            Created 
Info:        Working on 1984
Info:            Created 
Info:        Working on 3307
Info:            Created 
Info:        Working on 2335
Info:            Created 
Info:        Working on 3308
Info:            Created 
Info:        Working on 2670
Info:            Created 
Info:        Working on 2990
Info:            Created 
Info:        Working on 2992
Info:            Created 
Info:        Working on 2316
Info:            Created 
Info:        Working on 2666
Info:            Created 
Info:        Working on 1604
Info:            Created 
Info:        Working on 1967
Info:            Created 
Info:        Working on 2312
Info:            Created 
Info:        Working on 1592
Info:            Created 
Info:        Working on 1938
Info:            Created 
Info:        Working on 2303
Info:            Created 
Info:        Working on 2627
Info:            Created 
Info:        Working on 2283
Info:            Created 
Info:        Working on 1591
Info:            Created 
Info:        Working on 2296
Info:            Created 
Info:        Working on 2639
Info:            Created 
Info:        Working on 2976
Info:            Created 
Info:        Working on 2980
Info:            Created 
Info:        Working on 2646
Info:            Created 
Info:        Working on 1954
Info:            Created 
Info:        Working on 3299
Info:            Created 
Info:        Working on 2305
Info:            Created 
Info:        Working on 3619
Info:            Created 
Info:        Working on 2648
Info:            Created 
Info:        Working on 3620
Info:            Created 
Info:        Working on 2982
Info:            Created 
Info:        Working on 3302
Info:            Created 
Info:        Working on 3304
Info:            Created 
Info:        Working on 2629
Info:            Created 
Info:        Working on 2978
Info:            Created 
Info:        Working on 1942
Info:            Created 
Info:        Working on 2288
Info:            Created 
Info:        Working on 2625
Info:            Created 
Info:        Working on 1930
Info:            Created 
Info:        Working on 2259
Info:            Created 
Info:        Working on 2616
Info:            Created 
Info:        Working on 2939
Info:            Created 
Info:        Working on 2596
Info:            Created 
Info:        Working on 1929
Info:            Created 
Info:        Working on 2609
Info:            Created 
Info:        Working on 2951
Info:            Created 
Info:        Working on 3288
Info:            Created 
Info:        Working on 3292
Info:            Created 
Info:        Working on 2958
Info:            Created 
Info:        Working on 2275
Info:            Created 
Info:        Working on 3611
Info:            Created 
Info:        Working on 2618
Info:            Created 
Info:        Working on 3931
Info:            Created 
Info:        Working on 2960
Info:            Created 
Info:        Working on 3932
Info:            Created 
Info:        Working on 3294
Info:            Created 
Info:        Working on 3614
Info:            Created 
Info:        Working on 3616
Info:            Created 
Info:        Working on 2941
Info:            Created 
Info:        Working on 3290
Info:            Created 
Info:        Working on 2263
Info:            Created 
Info:        Working on 2601
Info:            Created 
Info:        Working on 2937
Info:            Created 
Info:        Working on 2251
Info:            Created 
Info:        Working on 2572
Info:            Created 
Info:        Working on 2928
Info:            Created 
Info:        Working on 3251
Info:            Created 
Info:        Working on 2908
Info:            Created 
Info:        Working on 2250
Info:            Created 
Info:        Working on 2921
Info:            Created 
Info:        Working on 3263
Info:            Created 
Info:        Working on 3600
Info:            Created 
Info:        Working on 3604
Info:            Created 
Info:        Working on 3270
Info:            Created 
Info:        Working on 2588
Info:            Created 
Info:        Working on 3923
Info:            Created 
Info:        Working on 2930
Info:            Created 
Info:        Working on 4243
Info:            Created 
Info:        Working on 3272
Info:            Created 
Info:        Working on 4244
Info:            Created 
Info:        Working on 3606
Info:            Created 
Info:        Working on 3926
Info:            Created 
Info:        Working on 3928
Info:            Created 
Info:        Working on 3253
Info:            Created 
Info:        Working on 3602
Info:            Created 
Info:        Working on 2576
Info:            Created 
Info:        Working on 2913
Info:            Created 
Info:        Working on 3249
Info:            Created 
Info:        Working on 2564
Info:            Created 
Info:        Working on 2884
Info:            Created 
Info:        Working on 3240
Info:            Created 
Info:        Working on 3563
Info:            Created 
Info:        Working on 3220
Info:            Created 
Info:        Working on 2563
Info:            Created 
Info:        Working on 3233
Info:            Created 
Info:        Working on 3575
Info:            Created 
Info:        Working on 3912
Info:            Created 
Info:        Working on 3916
Info:            Created 
Info:        Working on 3582
Info:            Created 
Info:        Working on 2900
Info:            Created 
Info:        Working on 4235
Info:            Created 
Info:        Working on 3242
Info:            Created 
Info:        Working on 4555
Info:            Created 
Info:        Working on 3584
Info:            Created 
Info:        Working on 4556
Info:            Created 
Info:        Working on 3918
Info:            Created 
Info:        Working on 4238
Info:            Created 
Info:        Working on 4240
Info:            Created 
Info:        Working on 3565
Info:            Created 
Info:        Working on 3914
Info:            Created 
Info:        Working on 2888
Info:            Created 
Info:        Working on 3225
Info:            Created 
Info:        Working on 3561
Info:            Created 
Info:        Working on 2876
Info:            Created 
Info:        Working on 3196
Info:            Created 
Info:        Working on 3552
Info:            Created 
Info:        Working on 3875
Info:            Created 
Info:        Working on 3532
Info:            Created 
Info:        Working on 2875
Info:            Created 
Info:        Working on 3545
Info:            Created 
Info:        Working on 3887
Info:            Created 
Info:        Working on 4224
Info:            Created 
Info:        Working on 4228
Info:            Created 
Info:        Working on 3894
Info:            Created 
Info:        Working on 3212
Info:            Created 
Info:        Working on 4547
Info:            Created 
Info:        Working on 3554
Info:            Created 
Info:        Working on 4867
Info:            Created 
Info:        Working on 3896
Info:            Created 
Info:        Working on 4868
Info:            Created 
Info:        Working on 4230
Info:            Created 
Info:        Working on 4550
Info:            Created 
Info:        Working on 4552
Info:            Created 
Info:        Working on 3877
Info:            Created 
Info:        Working on 4226
Info:            Created 
Info:        Working on 3200
Info:            Created 
Info:        Working on 3537
Info:            Created 
Info:        Working on 3873
Info:            Created 
Info:        Working on 3188
Info:            Created 
Info:        Working on 3508
Info:            Created 
Info:        Working on 3864
Info:            Created 
Info:        Working on 4187
Info:            Created 
Info:        Working on 3844
Info:            Created 
Info:        Working on 3187
Info:            Created 
Info:        Working on 3857
Info:            Created 
Info:        Working on 4199
Info:            Created 
Info:        Working on 4536
Info:            Created 
Info:        Working on 4540
Info:            Created 
Info:        Working on 4206
Info:            Created 
Info:        Working on 3524
Info:            Created 
Info:        Working on 4859
Info:            Created 
Info:        Working on 3866
Info:            Created 
Info:        Working on 5179
Info:            Created 
Info:        Working on 4208
Info:            Created 
Info:        Working on 5180
Info:            Created 
Info:        Working on 4542
Info:            Created 
Info:        Working on 4862
Info:            Created 
Info:        Working on 4864
Info:            Created 
Info:        Working on 4189
Info:            Created 
Info:        Working on 4538
Info:            Created 
Info:        Working on 3512
Info:            Created 
Info:        Working on 3849
Info:            Created 
Info:        Working on 4185
Info:            Created 
Info:        Working on 3500
Info:            Created 
Info:        Working on 3820
Info:            Created 
Info:        Working on 4176
Info:            Created 
Info:        Working on 4499
Info:            Created 
Info:        Working on 4156
Info:            Created 
Info:        Working on 3499
Info:            Created 
Info:        Working on 4169
Info:            Created 
Info:        Working on 4511
Info:            Created 
Info:        Working on 4848
Info:            Created 
Info:        Working on 4852
Info:            Created 
Info:        Working on 4518
Info:            Created 
Info:        Working on 3836
Info:            Created 
Info:        Working on 5171
Info:            Created 
Info:        Working on 4178
Info:            Created 
Info:        Working on 5491
Info:            Created 
Info:        Working on 4520
Info:            Created 
Info:        Working on 5492
Info:            Created 
Info:        Working on 4854
Info:            Created 
Info:        Working on 5174
Info:            Created 
Info:        Working on 5176
Info:            Created 
Info:        Working on 4501
Info:            Created 
Info:        Working on 4850
Info:            Created 
Info:        Working on 3824
Info:            Created 
Info:        Working on 4161
Info:            Created 
Info:        Working on 4497
Info:            Created 
Info:        Working on 3812
Info:            Created 
Info:        Working on 4132
Info:            Created 
Info:        Working on 4488
Info:            Created 
Info:        Working on 4811
Info:            Created 
Info:        Working on 4468
Info:            Created 
Info:        Working on 3811
Info:            Created 
Info:        Working on 4481
Info:            Created 
Info:        Working on 4823
Info:            Created 
Info:        Working on 5160
Info:            Created 
Info:        Working on 5164
Info:            Created 
Info:        Working on 4830
Info:            Created 
Info:        Working on 4148
Info:            Created 
Info:        Working on 5483
Info:            Created 
Info:        Working on 4490
Info:            Created 
Info:        Working on 5803
Info:            Created 
Info:        Working on 4832
Info:            Created 
Info:        Working on 5804
Info:            Created 
Info:        Working on 5166
Info:            Created 
Info:        Working on 5486
Info:            Created 
Info:        Working on 5488
Info:            Created 
Info:        Working on 4813
Info:            Created 
Info:        Working on 5162
Info:            Created 
Info:        Working on 4136
Info:            Created 
Info:        Working on 4473
Info:            Created 
Info:        Working on 4809
Info:            Created 
Info:        Working on 4124
Info:            Created 
Info:        Working on 4444
Info:            Created 
Info:        Working on 4800
Info:            Created 
Info:        Working on 5123
Info:            Created 
Info:        Working on 4780
Info:            Created 
Info:        Working on 4123
Info:            Created 
Info:        Working on 4793
Info:            Created 
Info:        Working on 5135
Info:            Created 
Info:        Working on 5472
Info:            Created 
Info:        Working on 5476
Info:            Created 
Info:        Working on 5142
Info:            Created 
Info:        Working on 4460
Info:            Created 
Info:        Working on 5795
Info:            Created 
Info:        Working on 4802
Info:            Created 
Info:        Working on 6115
Info:            Created 
Info:        Working on 5144
Info:            Created 
Info:        Working on 6116
Info:            Created 
Info:        Working on 5478
Info:            Created 
Info:        Working on 5798
Info:            Created 
Info:        Working on 5800
Info:            Created 
Info:        Working on 5125
Info:            Created 
Info:        Working on 5474
Info:            Created 
Info:        Working on 4448
Info:            Created 
Info:        Working on 4785
Info:            Created 
Info:        Working on 5121
Info:            Created 
Info:        Working on 4436
Info:            Created 
Info:        Working on 4756
Info:            Created 
Info:        Working on 5112
Info:            Created 
Info:        Working on 5435
Info:            Created 
Info:        Working on 5092
Info:            Created 
Info:        Working on 4435
Info:            Created 
Info:        Working on 5105
Info:            Created 
Info:        Working on 5447
Info:            Created 
Info:        Working on 5784
Info:            Created 
Info:        Working on 5788
Info:            Created 
Info:        Working on 5454
Info:            Created 
Info:        Working on 4772
Info:            Created 
Info:        Working on 6107
Info:            Created 
Info:        Working on 5114
Info:            Created 
Info:        Working on 6426
Info:            Created 
Info:        Working on 5456
Info:            Created 
Info:        Working on 6427
Info:            Created 
Info:        Working on 5790
Info:            Created 
Info:        Working on 6110
Info:            Created 
Info:        Working on 6112
Info:            Created 
Info:        Working on 5437
Info:            Created 
Info:        Working on 5786
Info:            Created 
Info:        Working on 4760
Info:            Created 
Info:        Working on 5097
Info:            Created 
Info:        Working on 5433
Info:            Created 
Info:        Working on 4748
Info:            Created 
Info:        Working on 5068
Info:            Created 
Info:        Working on 5424
Info:            Created 
Info:        Working on 5747
Info:            Created 
Info:        Working on 5404
Info:            Created 
Info:        Working on 4747
Info:            Created 
Info:        Working on 5417
Info:            Created 
Info:        Working on 5759
Info:            Created 
Info:        Working on 6096
Info:            Created 
Info:        Working on 6100
Info:            Created 
Info:        Working on 5766
Info:            Created 
Info:        Working on 5084
Info:            Created 
Info:        Working on 6418
Info:            Created 
Info:        Working on 5426
Info:            Created 
Info:        Working on 6736
Info:            Created 
Info:        Working on 5768
Info:            Created 
Info:        Working on 6737
Info:            Created 
Info:        Working on 6102
Info:            Created 
Info:        Working on 6421
Info:            Created 
Info:        Working on 6423
Info:            Created 
Info:        Working on 5749
Info:            Created 
Info:        Working on 6098
Info:            Created 
Info:        Working on 5072
Info:            Created 
Info:        Working on 5409
Info:            Created 
Info:        Working on 5745
Info:            Created 
Info:        Working on 5060
Info:            Created 
Info:        Working on 5380
Info:            Created 
Info:        Working on 5736
Info:            Created 
Info:        Working on 6059
Info:            Created 
Info:        Working on 5716
Info:            Created 
Info:        Working on 5059
Info:            Created 
Info:        Working on 5729
Info:            Created 
Info:        Working on 6071
Info:            Created 
Info:        Working on 6407
Info:            Created 
Info:        Working on 6411
Info:            Created 
Info:        Working on 6078
Info:            Created 
Info:        Working on 5396
Info:            Created 
Info:        Working on 6728
Info:            Created 
Info:        Working on 5738
Info:            Created 
Info:        Working on 7042
Info:            Created 
Info:        Working on 6080
Info:            Created 
Info:        Working on 7043
Info:            Created 
Info:        Working on 6413
Info:            Created 
Info:        Working on 6731
Info:            Created 
Info:        Working on 6733
Info:            Created 
Info:        Working on 6061
Info:            Created 
Info:        Working on 6409
Info:            Created 
Info:        Working on 5384
Info:            Created 
Info:        Working on 5721
Info:            Created 
Info:        Working on 6057
Info:            Created 
Info:        Working on 5372
Info:            Created 
Info:        Working on 5692
Info:            Created 
Info:        Working on 6048
Info:            Created 
Info:        Working on 6370
Info:            Created 
Info:        Working on 6028
Info:            Created 
Info:        Working on 5371
Info:            Created 
Info:        Working on 6041
Info:            Created 
Info:        Working on 6382
Info:            Created 
Info:        Working on 6717
Info:            Created 
Info:        Working on 6721
Info:            Created 
Info:        Working on 6389
Info:            Created 
Info:        Working on 5708
Info:            Created 
Info:        Working on 7034
Info:            Created 
Info:        Working on 6050
Info:            Created 
Info:        Working on 7337
Info:            Created 
Info:        Working on 6391
Info:            Created 
Info:        Working on 7338
Info:            Created 
Info:        Working on 6723
Info:            Created 
Info:        Working on 7037
Info:            Created 
Info:        Working on 7039
Info:            Created 
Info:        Working on 6372
Info:            Created 
Info:        Working on 6719
Info:            Created 
Info:        Working on 5696
Info:            Created 
Info:        Working on 6033
Info:            Created 
Info:        Working on 6368
Info:            Created 
Info:        Working on 5684
Info:            Created 
Info:        Working on 6004
Info:            Created 
Info:        Working on 6359
Info:            Created 
Info:        Working on 6680
Info:            Created 
Info:        Working on 6339
Info:            Created 
Info:        Working on 5683
Info:            Created 
Info:        Working on 6352
Info:            Created 
Info:        Working on 6692
Info:            Created 
Info:        Working on 7023
Info:            Created 
Info:        Working on 7027
Info:            Created 
Info:        Working on 6699
Info:            Created 
Info:        Working on 6020
Info:            Created 
Info:        Working on 7329
Info:            Created 
Info:        Working on 6361
Info:            Created 
Info:        Working on 7612
Info:            Created 
Info:        Working on 6701
Info:            Created 
Info:        Working on 7613
Info:            Created 
Info:        Working on 7029
Info:            Created 
Info:        Working on 7332
Info:            Created 
Info:        Working on 7334
Info:            Created 
Info:        Working on 6682
Info:            Created 
Info:        Working on 7025
Info:            Created 
Info:        Working on 6008
Info:            Created 
Info:        Working on 6344
Info:            Created 
Info:        Working on 6678
Info:            Created 
Info:        Working on 5996
Info:            Created 
Info:        Working on 6315
Info:            Created 
Info:        Working on 6669
Info:            Created 
Info:        Working on 6986
Info:            Created 
Info:        Working on 6649
Info:            Created 
Info:        Working on 5995
Info:            Created 
Info:        Working on 6662
Info:            Created 
Info:        Working on 6998
Info:            Created 
Info:        Working on 7318
Info:            Created 
Info:        Working on 7322
Info:            Created 
Info:        Working on 7005
Info:            Created 
Info:        Working on 6331
Info:            Created 
Info:        Working on 7604
Info:            Created 
Info:        Working on 6671
Info:            Created 
Info:        Working on 7862
Info:            Created 
Info:        Working on 7007
Info:            Created 
Info:        Working on 7863
Info:            Created 
Info:        Working on 7324
Info:            Created 
Info:        Working on 7607
Info:            Created 
Info:        Working on 7609
Info:            Created 
Info:        Working on 6988
Info:            Created 
Info:        Working on 7320
Info:            Created 
Info:        Working on 6319
Info:            Created 
Info:        Working on 6654
Info:            Created 
Info:        Working on 6984
Info:            Created 
Info:        Working on 6307
Info:            Created 
Info:        Working on 6625
Info:            Created 
Info:        Working on 6975
Info:            Created 
Info:        Working on 7281
Info:            Created 
Info:        Working on 6955
Info:            Created 
Info:        Working on 6306
Info:            Created 
Info:        Working on 6968
Info:            Created 
Info:        Working on 7293
Info:            Created 
Info:        Working on 7593
Info:            Created 
Info:        Working on 7597
Info:            Created 
Info:        Working on 7300
Info:            Created 
Info:        Working on 6641
Info:            Created 
Info:        Working on 7854
Info:            Created 
Info:        Working on 6977
Info:            Created 
Info:        Working on 8078
Info:            Created 
Info:        Working on 7302
Info:            Created 
Info:        Working on 8079
Info:            Created 
Info:        Working on 7599
Info:            Created 
Info:        Working on 7857
Info:            Created 
Info:        Working on 7859
Info:            Created 
Info:        Working on 7283
Info:            Created 
Info:        Working on 7595
Info:            Created 
Info:        Working on 6629
Info:            Created 
Info:        Working on 6960
Info:            Created 
Info:        Working on 7279
Info:            Created 
Info:        Working on 6617
Info:            Created 
Info:        Working on 6931
Info:            Created 
Info:        Working on 7270
Info:            Created 
Info:        Working on 7556
Info:            Created 
Info:        Working on 7250
Info:            Created 
Info:        Working on 6616
Info:            Created 
Info:        Working on 7263
Info:            Created 
Info:        Working on 7568
Info:            Created 
Info:        Working on 7843
Info:            Created 
Info:        Working on 7847
Info:            Created 
Info:        Working on 7575
Info:            Created 
Info:        Working on 6947
Info:            Created 
Info:        Working on 8070
Info:            Created 
Info:        Working on 7272
Info:            Created 
Info:        Working on 8253
Info:            Created 
Info:        Working on 7577
Info:            Created 
Info:        Working on 8254
Info:            Created 
Info:        Working on 7849
Info:            Created 
Info:        Working on 8073
Info:            Created 
Info:        Working on 8075
Info:            Created 
Info:        Working on 7558
Info:            Created 
Info:        Working on 7845
Info:            Created 
Info:        Working on 6935
Info:            Created 
Info:        Working on 7255
Info:            Created 
Info:        Working on 7554
Info:            Created 
Info:        Working on 6923
Info:            Created 
Info:        Working on 7226
Info:            Created 
Info:        Working on 7545
Info:            Created 
Info:        Working on 7806
Info:            Created 
Info:        Working on 7525
Info:            Created 
Info:        Working on 6922
Info:            Created 
Info:        Working on 7538
Info:            Created 
Info:        Working on 7818
Info:            Created 
Info:        Working on 8059
Info:            Created 
Info:        Working on 8063
Info:            Created 
Info:        Working on 7825
Info:            Created 
Info:        Working on 7242
Info:            Created 
Info:        Working on 8245
Info:            Created 
Info:        Working on 7547
Info:            Created 
Info:        Working on 8387
Info:            Created 
Info:        Working on 7827
Info:            Created 
Info:        Working on 8388
Info:            Created 
Info:        Working on 8065
Info:            Created 
Info:        Working on 8248
Info:            Created 
Info:        Working on 8250
Info:            Created 
Info:        Working on 7808
Info:            Created 
Info:        Working on 8061
Info:            Created 
Info:        Working on 7230
Info:            Created 
Info:        Working on 7530
Info:            Created 
Info:        Working on 7804
Info:            Created 
Info:        Working on 7218
Info:            Created 
Info:        Working on 7501
Info:            Created 
Info:        Working on 7795
Info:            Created 
Info:        Working on 8022
Info:            Created 
Info:        Working on 7775
Info:            Created 
Info:        Working on 7217
Info:            Created 
Info:        Working on 7788
Info:            Created 
Info:        Working on 8034
Info:            Created 
Info:        Working on 8234
Info:            Created 
Info:        Working on 8238
Info:            Created 
Info:        Working on 8041
Info:            Created 
Info:        Working on 7517
Info:            Created 
Info:        Working on 8379
Info:            Created 
Info:        Working on 7797
Info:            Created 
Info:        Working on 8487
Info:            Created 
Info:        Working on 8043
Info:            Created 
Info:        Working on 8488
Info:            Created 
Info:        Working on 8240
Info:            Created 
Info:        Working on 8382
Info:            Created 
Info:        Working on 8384
Info:            Created 
Info:        Working on 8024
Info:            Created 
Info:        Working on 8236
Info:            Created 
Info:        Working on 7505
Info:            Created 
Info:        Working on 7780
Info:            Created 
Info:        Working on 8020
Info:            Created 
Info:        Working on 458
Info:            Created 
Info:        Working on 642
Info:            Created 
Info:        Working on 914
Info:            Created 
Info:        Working on 1199
Info:            Created 
Info:        Working on 893
Info:            Created 
Info:        Working on 457
Info:            Created 
Info:        Working on 907
Info:            Created 
Info:        Working on 1212
Info:            Created 
Info:        Working on 1550
Info:            Created 
Info:        Working on 1554
Info:            Created 
Info:        Working on 1220
Info:            Created 
Info:        Working on 657
Info:            Created 
Info:        Working on 646
Info:            Created 
Info:        Working on 1201
Info:            Created 
Info:        Working on 899
Info:            Created 
Info:        Working on 1890
Info:            Created 
Info:        Working on 1203
Info:            Created 
Info:        Working on 2215
Info:            Created 
Info:        Working on 1544
Info:            Created 
Info:        Working on 2214
Info:            Created 
Info:        Working on 1891
Info:            Created 
Info:        Working on 1887
Info:            Created 
Info:        Working on 1894
Info:            Created 
Info:        Working on 1556
Info:            Created 
Info:        Working on 1197
Info:            Created 
Info:        Working on 634
Info:            Created 
Info:        Working on 870
Info:            Created 
Info:        Working on 1190
Info:            Created 
Info:        Working on 1512
Info:            Created 
Info:        Working on 1169
Info:            Created 
Info:        Working on 633
Info:            Created 
Info:        Working on 1183
Info:            Created 
Info:        Working on 1525
Info:            Created 
Info:        Working on 1876
Info:            Created 
Info:        Working on 1880
Info:            Created 
Info:        Working on 1533
Info:            Created 
Info:        Working on 885
Info:            Created 
Info:        Working on 874
Info:            Created 
Info:        Working on 1514
Info:            Created 
Info:        Working on 1175
Info:            Created 
Info:        Working on 2208
Info:            Created 
Info:        Working on 1516
Info:            Created 
Info:        Working on 2528
Info:            Created 
Info:        Working on 1870
Info:            Created 
Info:        Working on 2527
Info:            Created 
Info:        Working on 2209
Info:            Created 
Info:        Working on 2205
Info:            Created 
Info:        Working on 2212
Info:            Created 
Info:        Working on 1882
Info:            Created 
Info:        Working on 1510
Info:            Created 
Info:        Working on 862
Info:            Created 
Info:        Working on 1146
Info:            Created 
Info:        Working on 1503
Info:            Created 
Info:        Working on 1838
Info:            Created 
Info:        Working on 1482
Info:            Created 
Info:        Working on 861
Info:            Created 
Info:        Working on 1496
Info:            Created 
Info:        Working on 1851
Info:            Created 
Info:        Working on 2194
Info:            Created 
Info:        Working on 2198
Info:            Created 
Info:        Working on 1859
Info:            Created 
Info:        Working on 1161
Info:            Created 
Info:        Working on 1150
Info:            Created 
Info:        Working on 1840
Info:            Created 
Info:        Working on 1488
Info:            Created 
Info:        Working on 2521
Info:            Created 
Info:        Working on 1842
Info:            Created 
Info:        Working on 2840
Info:            Created 
Info:        Working on 2188
Info:            Created 
Info:        Working on 2839
Info:            Created 
Info:        Working on 2522
Info:            Created 
Info:        Working on 2518
Info:            Created 
Info:        Working on 2525
Info:            Created 
Info:        Working on 2200
Info:            Created 
Info:        Working on 1836
Info:            Created 
Info:        Working on 1138
Info:            Created 
Info:        Working on 1459
Info:            Created 
Info:        Working on 1829
Info:            Created 
Info:        Working on 2156
Info:            Created 
Info:        Working on 1808
Info:            Created 
Info:        Working on 1137
Info:            Created 
Info:        Working on 1822
Info:            Created 
Info:        Working on 2169
Info:            Created 
Info:        Working on 2507
Info:            Created 
Info:        Working on 2511
Info:            Created 
Info:        Working on 2177
Info:            Created 
Info:        Working on 1474
Info:            Created 
Info:        Working on 1463
Info:            Created 
Info:        Working on 2158
Info:            Created 
Info:        Working on 1814
Info:            Created 
Info:        Working on 2833
Info:            Created 
Info:        Working on 2160
Info:            Created 
Info:        Working on 3152
Info:            Created 
Info:        Working on 2501
Info:            Created 
Info:        Working on 3151
Info:            Created 
Info:        Working on 2834
Info:            Created 
Info:        Working on 2830
Info:            Created 
Info:        Working on 2837
Info:            Created 
Info:        Working on 2513
Info:            Created 
Info:        Working on 2154
Info:            Created 
Info:        Working on 1451
Info:            Created 
Info:        Working on 1785
Info:            Created 
Info:        Working on 2147
Info:            Created 
Info:        Working on 2469
Info:            Created 
Info:        Working on 2126
Info:            Created 
Info:        Working on 1450
Info:            Created 
Info:        Working on 2140
Info:            Created 
Info:        Working on 2482
Info:            Created 
Info:        Working on 2819
Info:            Created 
Info:        Working on 2823
Info:            Created 
Info:        Working on 2490
Info:            Created 
Info:        Working on 1800
Info:            Created 
Info:        Working on 1789
Info:            Created 
Info:        Working on 2471
Info:            Created 
Info:        Working on 2132
Info:            Created 
Info:        Working on 3145
Info:            Created 
Info:        Working on 2473
Info:            Created 
Info:        Working on 3464
Info:            Created 
Info:        Working on 2813
Info:            Created 
Info:        Working on 3463
Info:            Created 
Info:        Working on 3146
Info:            Created 
Info:        Working on 3142
Info:            Created 
Info:        Working on 3149
Info:            Created 
Info:        Working on 2825
Info:            Created 
Info:        Working on 2467
Info:            Created 
Info:        Working on 1777
Info:            Created 
Info:        Working on 2103
Info:            Created 
Info:        Working on 2460
Info:            Created 
Info:        Working on 2781
Info:            Created 
Info:        Working on 2439
Info:            Created 
Info:        Working on 1776
Info:            Created 
Info:        Working on 2453
Info:            Created 
Info:        Working on 2794
Info:            Created 
Info:        Working on 3131
Info:            Created 
Info:        Working on 3135
Info:            Created 
Info:        Working on 2802
Info:            Created 
Info:        Working on 2118
Info:            Created 
Info:        Working on 2107
Info:            Created 
Info:        Working on 2783
Info:            Created 
Info:        Working on 2445
Info:            Created 
Info:        Working on 3457
Info:            Created 
Info:        Working on 2785
Info:            Created 
Info:        Working on 3776
Info:            Created 
Info:        Working on 3125
Info:            Created 
Info:        Working on 3775
Info:            Created 
Info:        Working on 3458
Info:            Created 
Info:        Working on 3454
Info:            Created 
Info:        Working on 3461
Info:            Created 
Info:        Working on 3137
Info:            Created 
Info:        Working on 2779
Info:            Created 
Info:        Working on 2095
Info:            Created 
Info:        Working on 2416
Info:            Created 
Info:        Working on 2772
Info:            Created 
Info:        Working on 3093
Info:            Created 
Info:        Working on 2751
Info:            Created 
Info:        Working on 2094
Info:            Created 
Info:        Working on 2765
Info:            Created 
Info:        Working on 3106
Info:            Created 
Info:        Working on 3443
Info:            Created 
Info:        Working on 3447
Info:            Created 
Info:        Working on 3114
Info:            Created 
Info:        Working on 2431
Info:            Created 
Info:        Working on 2420
Info:            Created 
Info:        Working on 3095
Info:            Created 
Info:        Working on 2757
Info:            Created 
Info:        Working on 3769
Info:            Created 
Info:        Working on 3097
Info:            Created 
Info:        Working on 4088
Info:            Created 
Info:        Working on 3437
Info:            Created 
Info:        Working on 4087
Info:            Created 
Info:        Working on 3770
Info:            Created 
Info:        Working on 3766
Info:            Created 
Info:        Working on 3773
Info:            Created 
Info:        Working on 3449
Info:            Created 
Info:        Working on 3091
Info:            Created 
Info:        Working on 2408
Info:            Created 
Info:        Working on 2728
Info:            Created 
Info:        Working on 3084
Info:            Created 
Info:        Working on 3405
Info:            Created 
Info:        Working on 3063
Info:            Created 
Info:        Working on 2407
Info:            Created 
Info:        Working on 3077
Info:            Created 
Info:        Working on 3418
Info:            Created 
Info:        Working on 3755
Info:            Created 
Info:        Working on 3759
Info:            Created 
Info:        Working on 3426
Info:            Created 
Info:        Working on 2743
Info:            Created 
Info:        Working on 2732
Info:            Created 
Info:        Working on 3407
Info:            Created 
Info:        Working on 3069
Info:            Created 
Info:        Working on 4081
Info:            Created 
Info:        Working on 3409
Info:            Created 
Info:        Working on 4400
Info:            Created 
Info:        Working on 3749
Info:            Created 
Info:        Working on 4399
Info:            Created 
Info:        Working on 4082
Info:            Created 
Info:        Working on 4078
Info:            Created 
Info:        Working on 4085
Info:            Created 
Info:        Working on 3761
Info:            Created 
Info:        Working on 3403
Info:            Created 
Info:        Working on 2720
Info:            Created 
Info:        Working on 3040
Info:            Created 
Info:        Working on 3396
Info:            Created 
Info:        Working on 3717
Info:            Created 
Info:        Working on 3375
Info:            Created 
Info:        Working on 2719
Info:            Created 
Info:        Working on 3389
Info:            Created 
Info:        Working on 3730
Info:            Created 
Info:        Working on 4067
Info:            Created 
Info:        Working on 4071
Info:            Created 
Info:        Working on 3738
Info:            Created 
Info:        Working on 3055
Info:            Created 
Info:        Working on 3044
Info:            Created 
Info:        Working on 3719
Info:            Created 
Info:        Working on 3381
Info:            Created 
Info:        Working on 4393
Info:            Created 
Info:        Working on 3721
Info:            Created 
Info:        Working on 4712
Info:            Created 
Info:        Working on 4061
Info:            Created 
Info:        Working on 4711
Info:            Created 
Info:        Working on 4394
Info:            Created 
Info:        Working on 4390
Info:            Created 
Info:        Working on 4397
Info:            Created 
Info:        Working on 4073
Info:            Created 
Info:        Working on 3715
Info:            Created 
Info:        Working on 3032
Info:            Created 
Info:        Working on 3352
Info:            Created 
Info:        Working on 3708
Info:            Created 
Info:        Working on 4029
Info:            Created 
Info:        Working on 3687
Info:            Created 
Info:        Working on 3031
Info:            Created 
Info:        Working on 3701
Info:            Created 
Info:        Working on 4042
Info:            Created 
Info:        Working on 4379
Info:            Created 
Info:        Working on 4383
Info:            Created 
Info:        Working on 4050
Info:            Created 
Info:        Working on 3367
Info:            Created 
Info:        Working on 3356
Info:            Created 
Info:        Working on 4031
Info:            Created 
Info:        Working on 3693
Info:            Created 
Info:        Working on 4705
Info:            Created 
Info:        Working on 4033
Info:            Created 
Info:        Working on 5024
Info:            Created 
Info:        Working on 4373
Info:            Created 
Info:        Working on 5023
Info:            Created 
Info:        Working on 4706
Info:            Created 
Info:        Working on 4702
Info:            Created 
Info:        Working on 4709
Info:            Created 
Info:        Working on 4385
Info:            Created 
Info:        Working on 4027
Info:            Created 
Info:        Working on 3344
Info:            Created 
Info:        Working on 3664
Info:            Created 
Info:        Working on 4020
Info:            Created 
Info:        Working on 4341
Info:            Created 
Info:        Working on 3999
Info:            Created 
Info:        Working on 3343
Info:            Created 
Info:        Working on 4013
Info:            Created 
Info:        Working on 4354
Info:            Created 
Info:        Working on 4691
Info:            Created 
Info:        Working on 4695
Info:            Created 
Info:        Working on 4362
Info:            Created 
Info:        Working on 3679
Info:            Created 
Info:        Working on 3668
Info:            Created 
Info:        Working on 4343
Info:            Created 
Info:        Working on 4005
Info:            Created 
Info:        Working on 5017
Info:            Created 
Info:        Working on 4345
Info:            Created 
Info:        Working on 5336
Info:            Created 
Info:        Working on 4685
Info:            Created 
Info:        Working on 5335
Info:            Created 
Info:        Working on 5018
Info:            Created 
Info:        Working on 5014
Info:            Created 
Info:        Working on 5021
Info:            Created 
Info:        Working on 4697
Info:            Created 
Info:        Working on 4339
Info:            Created 
Info:        Working on 3656
Info:            Created 
Info:        Working on 3976
Info:            Created 
Info:        Working on 4332
Info:            Created 
Info:        Working on 4653
Info:            Created 
Info:        Working on 4311
Info:            Created 
Info:        Working on 3655
Info:            Created 
Info:        Working on 4325
Info:            Created 
Info:        Working on 4666
Info:            Created 
Info:        Working on 5003
Info:            Created 
Info:        Working on 5007
Info:            Created 
Info:        Working on 4674
Info:            Created 
Info:        Working on 3991
Info:            Created 
Info:        Working on 3980
Info:            Created 
Info:        Working on 4655
Info:            Created 
Info:        Working on 4317
Info:            Created 
Info:        Working on 5329
Info:            Created 
Info:        Working on 4657
Info:            Created 
Info:        Working on 5648
Info:            Created 
Info:        Working on 4997
Info:            Created 
Info:        Working on 5647
Info:            Created 
Info:        Working on 5330
Info:            Created 
Info:        Working on 5326
Info:            Created 
Info:        Working on 5333
Info:            Created 
Info:        Working on 5009
Info:            Created 
Info:        Working on 4651
Info:            Created 
Info:        Working on 3968
Info:            Created 
Info:        Working on 4288
Info:            Created 
Info:        Working on 4644
Info:            Created 
Info:        Working on 4965
Info:            Created 
Info:        Working on 4623
Info:            Created 
Info:        Working on 3967
Info:            Created 
Info:        Working on 4637
Info:            Created 
Info:        Working on 4978
Info:            Created 
Info:        Working on 5315
Info:            Created 
Info:        Working on 5319
Info:            Created 
Info:        Working on 4986
Info:            Created 
Info:        Working on 4303
Info:            Created 
Info:        Working on 4292
Info:            Created 
Info:        Working on 4967
Info:            Created 
Info:        Working on 4629
Info:            Created 
Info:        Working on 5641
Info:            Created 
Info:        Working on 4969
Info:            Created 
Info:        Working on 5960
Info:            Created 
Info:        Working on 5309
Info:            Created 
Info:        Working on 5959
Info:            Created 
Info:        Working on 5642
Info:            Created 
Info:        Working on 5638
Info:            Created 
Info:        Working on 5645
Info:            Created 
Info:        Working on 5321
Info:            Created 
Info:        Working on 4963
Info:            Created 
Info:        Working on 4280
Info:            Created 
Info:        Working on 4600
Info:            Created 
Info:        Working on 4956
Info:            Created 
Info:        Working on 5277
Info:            Created 
Info:        Working on 4935
Info:            Created 
Info:        Working on 4279
Info:            Created 
Info:        Working on 4949
Info:            Created 
Info:        Working on 5290
Info:            Created 
Info:        Working on 5627
Info:            Created 
Info:        Working on 5631
Info:            Created 
Info:        Working on 5298
Info:            Created 
Info:        Working on 4615
Info:            Created 
Info:        Working on 4604
Info:            Created 
Info:        Working on 5279
Info:            Created 
Info:        Working on 4941
Info:            Created 
Info:        Working on 5953
Info:            Created 
Info:        Working on 5281
Info:            Created 
Info:        Working on 6272
Info:            Created 
Info:        Working on 5621
Info:            Created 
Info:        Working on 6271
Info:            Created 
Info:        Working on 5954
Info:            Created 
Info:        Working on 5950
Info:            Created 
Info:        Working on 5957
Info:            Created 
Info:        Working on 5633
Info:            Created 
Info:        Working on 5275
Info:            Created 
Info:        Working on 4592
Info:            Created 
Info:        Working on 4912
Info:            Created 
Info:        Working on 5268
Info:            Created 
Info:        Working on 5589
Info:            Created 
Info:        Working on 5247
Info:            Created 
Info:        Working on 4591
Info:            Created 
Info:        Working on 5261
Info:            Created 
Info:        Working on 5602
Info:            Created 
Info:        Working on 5939
Info:            Created 
Info:        Working on 5943
Info:            Created 
Info:        Working on 5610
Info:            Created 
Info:        Working on 4927
Info:            Created 
Info:        Working on 4916
Info:            Created 
Info:        Working on 5591
Info:            Created 
Info:        Working on 5253
Info:            Created 
Info:        Working on 6265
Info:            Created 
Info:        Working on 5593
Info:            Created 
Info:        Working on 6583
Info:            Created 
Info:        Working on 5933
Info:            Created 
Info:        Working on 6582
Info:            Created 
Info:        Working on 6266
Info:            Created 
Info:        Working on 6262
Info:            Created 
Info:        Working on 6269
Info:            Created 
Info:        Working on 5945
Info:            Created 
Info:        Working on 5587
Info:            Created 
Info:        Working on 4904
Info:            Created 
Info:        Working on 5224
Info:            Created 
Info:        Working on 5580
Info:            Created 
Info:        Working on 5901
Info:            Created 
Info:        Working on 5559
Info:            Created 
Info:        Working on 4903
Info:            Created 
Info:        Working on 5573
Info:            Created 
Info:        Working on 5914
Info:            Created 
Info:        Working on 6251
Info:            Created 
Info:        Working on 6255
Info:            Created 
Info:        Working on 5922
Info:            Created 
Info:        Working on 5239
Info:            Created 
Info:        Working on 5228
Info:            Created 
Info:        Working on 5903
Info:            Created 
Info:        Working on 5565
Info:            Created 
Info:        Working on 6576
Info:            Created 
Info:        Working on 5905
Info:            Created 
Info:        Working on 6893
Info:            Created 
Info:        Working on 6245
Info:            Created 
Info:        Working on 6892
Info:            Created 
Info:        Working on 6577
Info:            Created 
Info:        Working on 6573
Info:            Created 
Info:        Working on 6580
Info:            Created 
Info:        Working on 6257
Info:            Created 
Info:        Working on 5899
Info:            Created 
Info:        Working on 5216
Info:            Created 
Info:        Working on 5536
Info:            Created 
Info:        Working on 5892
Info:            Created 
Info:        Working on 6213
Info:            Created 
Info:        Working on 5871
Info:            Created 
Info:        Working on 5215
Info:            Created 
Info:        Working on 5885
Info:            Created 
Info:        Working on 6226
Info:            Created 
Info:        Working on 6562
Info:            Created 
Info:        Working on 6566
Info:            Created 
Info:        Working on 6234
Info:            Created 
Info:        Working on 5551
Info:            Created 
Info:        Working on 5540
Info:            Created 
Info:        Working on 6215
Info:            Created 
Info:        Working on 5877
Info:            Created 
Info:        Working on 6886
Info:            Created 
Info:        Working on 6217
Info:            Created 
Info:        Working on 7199
Info:            Created 
Info:        Working on 6556
Info:            Created 
Info:        Working on 7198
Info:            Created 
Info:        Working on 6887
Info:            Created 
Info:        Working on 6883
Info:            Created 
Info:        Working on 6890
Info:            Created 
Info:        Working on 6568
Info:            Created 
Info:        Working on 6211
Info:            Created 
Info:        Working on 5528
Info:            Created 
Info:        Working on 5848
Info:            Created 
Info:        Working on 6204
Info:            Created 
Info:        Working on 6524
Info:            Created 
Info:        Working on 6183
Info:            Created 
Info:        Working on 5527
Info:            Created 
Info:        Working on 6197
Info:            Created 
Info:        Working on 6537
Info:            Created 
Info:        Working on 6872
Info:            Created 
Info:        Working on 6876
Info:            Created 
Info:        Working on 6545
Info:            Created 
Info:        Working on 5863
Info:            Created 
Info:        Working on 5852
Info:            Created 
Info:        Working on 6526
Info:            Created 
Info:        Working on 6189
Info:            Created 
Info:        Working on 7192
Info:            Created 
Info:        Working on 6528
Info:            Created 
Info:        Working on 7493
Info:            Created 
Info:        Working on 6866
Info:            Created 
Info:        Working on 7492
Info:            Created 
Info:        Working on 7193
Info:            Created 
Info:        Working on 7189
Info:            Created 
Info:        Working on 7196
Info:            Created 
Info:        Working on 6878
Info:            Created 
Info:        Working on 6522
Info:            Created 
Info:        Working on 5840
Info:            Created 
Info:        Working on 6160
Info:            Created 
Info:        Working on 6515
Info:            Created 
Info:        Working on 6834
Info:            Created 
Info:        Working on 6494
Info:            Created 
Info:        Working on 5839
Info:            Created 
Info:        Working on 6508
Info:            Created 
Info:        Working on 6847
Info:            Created 
Info:        Working on 7178
Info:            Created 
Info:        Working on 7182
Info:            Created 
Info:        Working on 6855
Info:            Created 
Info:        Working on 6175
Info:            Created 
Info:        Working on 6164
Info:            Created 
Info:        Working on 6836
Info:            Created 
Info:        Working on 6500
Info:            Created 
Info:        Working on 7486
Info:            Created 
Info:        Working on 6838
Info:            Created 
Info:        Working on 7767
Info:            Created 
Info:        Working on 7172
Info:            Created 
Info:        Working on 7766
Info:            Created 
Info:        Working on 7487
Info:            Created 
Info:        Working on 7483
Info:            Created 
Info:        Working on 7490
Info:            Created 
Info:        Working on 7184
Info:            Created 
Info:        Working on 6832
Info:            Created 
Info:        Working on 6152
Info:            Created 
Info:        Working on 6471
Info:            Created 
Info:        Working on 6825
Info:            Created 
Info:        Working on 7140
Info:            Created 
Info:        Working on 6804
Info:            Created 
Info:        Working on 6151
Info:            Created 
Info:        Working on 6818
Info:            Created 
Info:        Working on 7153
Info:            Created 
Info:        Working on 7472
Info:            Created 
Info:        Working on 7476
Info:            Created 
Info:        Working on 7161
Info:            Created 
Info:        Working on 6486
Info:            Created 
Info:        Working on 6475
Info:            Created 
Info:        Working on 7142
Info:            Created 
Info:        Working on 6810
Info:            Created 
Info:        Working on 7760
Info:            Created 
Info:        Working on 7144
Info:            Created 
Info:        Working on 8013
Info:            Created 
Info:        Working on 7466
Info:            Created 
Info:        Working on 8012
Info:            Created 
Info:        Working on 7761
Info:            Created 
Info:        Working on 7757
Info:            Created 
Info:        Working on 7764
Info:            Created 
Info:        Working on 7478
Info:            Created 
Info:        Working on 7138
Info:            Created 
Info:        Working on 6463
Info:            Created 
Info:        Working on 6781
Info:            Created 
Info:        Working on 7131
Info:            Created 
Info:        Working on 7434
Info:            Created 
Info:        Working on 7110
Info:            Created 
Info:        Working on 6462
Info:            Created 
Info:        Working on 7124
Info:            Created 
Info:        Working on 7447
Info:            Created 
Info:        Working on 7746
Info:            Created 
Info:        Working on 7750
Info:            Created 
Info:        Working on 7455
Info:            Created 
Info:        Working on 6796
Info:            Created 
Info:        Working on 6785
Info:            Created 
Info:        Working on 7436
Info:            Created 
Info:        Working on 7116
Info:            Created 
Info:        Working on 8006
Info:            Created 
Info:        Working on 7438
Info:            Created 
Info:        Working on 8218
Info:            Created 
Info:        Working on 7740
Info:            Created 
Info:        Working on 8217
Info:            Created 
Info:        Working on 8007
Info:            Created 
Info:        Working on 8003
Info:            Created 
Info:        Working on 8010
Info:            Created 
Info:        Working on 7752
Info:            Created 
Info:        Working on 7432
Info:            Created 
Info:        Working on 6773
Info:            Created 
Info:        Working on 7087
Info:            Created 
Info:        Working on 7425
Info:            Created 
Info:        Working on 7708
Info:            Created 
Info:        Working on 7404
Info:            Created 
Info:        Working on 6772
Info:            Created 
Info:        Working on 7418
Info:            Created 
Info:        Working on 7721
Info:            Created 
Info:        Working on 7992
Info:            Created 
Info:        Working on 7996
Info:            Created 
Info:        Working on 7729
Info:            Created 
Info:        Working on 7102
Info:            Created 
Info:        Working on 7091
Info:            Created 
Info:        Working on 7710
Info:            Created 
Info:        Working on 7410
Info:            Created 
Info:        Working on 8211
Info:            Created 
Info:        Working on 7712
Info:            Created 
Info:        Working on 8374
Info:            Created 
Info:        Working on 7986
Info:            Created 
Info:        Working on 8373
Info:            Created 
Info:        Working on 8212
Info:            Created 
Info:        Working on 8208
Info:            Created 
Info:        Working on 8215
Info:            Created 
Info:        Working on 7998
Info:            Created 
Info:        Working on 7706
Info:            Created 
Info:        Working on 7079
Info:            Created 
Info:        Working on 7381
Info:            Created 
Info:        Working on 7699
Info:            Created 
Info:        Working on 7954
Info:            Created 
Info:        Working on 7678
Info:            Created 
Info:        Working on 7078
Info:            Created 
Info:        Working on 7692
Info:            Created 
Info:        Working on 7967
Info:            Created 
Info:        Working on 8197
Info:            Created 
Info:        Working on 8201
Info:            Created 
Info:        Working on 7975
Info:            Created 
Info:        Working on 7396
Info:            Created 
Info:        Working on 7385
Info:            Created 
Info:        Working on 7956
Info:            Created 
Info:        Working on 7684
Info:            Created 
Info:        Working on 8367
Info:            Created 
Info:        Working on 7958
Info:            Created 
Info:        Working on 8485
Info:            Created 
Info:        Working on 8191
Info:            Created 
Info:        Working on 8484
Info:            Created 
Info:        Working on 8368
Info:            Created 
Info:        Working on 8364
Info:            Created 
Info:        Working on 8371
Info:            Created 
Info:        Working on 8203
Info:            Created 
Info:        Working on 7952
Info:            Created 
Info:        Working on 7373
Info:            Created 
Info:        Working on 7655
Info:            Created 
Info:        Working on 7945
Info:            Created 
Info:        Working on 8159
Info:            Created 
Info:        Working on 7924
Info:            Created 
Info:        Working on 7372
Info:            Created 
Info:        Working on 7938
Info:            Created 
Info:        Working on 8172
Info:            Created 
Info:        Working on 8353
Info:            Created 
Info:        Working on 8357
Info:            Created 
Info:        Working on 8180
Info:            Created 
Info:        Working on 7670
Info:            Created 
Info:        Working on 7659
Info:            Created 
Info:        Working on 8161
Info:            Created 
Info:        Working on 7930
Info:            Created 
Info:        Working on 8478
Info:            Created 
Info:        Working on 8163
Info:            Created 
Info:        Working on 8556
Info:            Created 
Info:        Working on 8347
Info:            Created 
Info:        Working on 8555
Info:            Created 
Info:        Working on 8479
Info:            Created 
Info:        Working on 8475
Info:            Created 
Info:        Working on 8482
Info:            Created 
Info:        Working on 8359
Info:            Created 
Info:        Working on 8157
Info:            Created 
Info:        Working on 7647
Info:            Created 
Info:        Working on 7901
Info:            Created 
Info:        Working on 8150
Info:            Created 
Info:        Working on 8315
Info:            Created 
Info:        Working on 8129
Info:            Created 
Info:        Working on 7646
Info:            Created 
Info:        Working on 8143
Info:            Created 
Info:        Working on 8328
Info:            Created 
Info:        Working on 8464
Info:            Created 
Info:        Working on 8468
Info:            Created 
Info:        Working on 8336
Info:            Created 
Info:        Working on 7916
Info:            Created 
Info:        Working on 7905
Info:            Created 
Info:        Working on 8317
Info:            Created 
Info:        Working on 8135
Info:            Created 
Info:        Working on 8549
Info:            Created 
Info:        Working on 8319
Info:            Created 
Info:        Working on 8594
Info:            Created 
Info:        Working on 8458
Info:            Created 
Info:        Working on 8593
Info:            Created 
Info:        Working on 8550
Info:            Created 
Info:        Working on 8546
Info:            Created 
Info:        Working on 8553
Info:            Created 
Info:        Working on 8470
Info:            Created 
Info:        Working on 8313
Info:            Created 
Info:        Working on 7893
Info:            Created 
Info:        Working on 8106
Info:            Created 
Info:        Working on 8306
Info:            Created 
Info:        Working on 8426
Info:            Created 
Info:        Working on 8285
Info:            Created 
Info:        Working on 7892
Info:            Created 
Info:        Working on 8299
Info:            Created 
Info:        Working on 8439
Info:            Created 
Info:        Working on 8535
Info:            Created 
Info:        Working on 8539
Info:            Created 
Info:        Working on 8447
Info:            Created 
Info:        Working on 8121
Info:            Created 
Info:        Working on 8110
Info:            Created 
Info:        Working on 8428
Info:            Created 
Info:        Working on 8291
Info:            Created 
Info:        Working on 8587
Info:            Created 
Info:        Working on 8430
Info:            Created 
Info:        Working on 8609
Info:            Created 
Info:        Working on 8529
Info:            Created 
Info:        Working on 8608
Info:            Created 
Info:        Working on 8588
Info:            Created 
Info:        Working on 8584
Info:            Created 
Info:        Working on 8591
Info:            Created 
Info:        Working on 8541
Info:            Created 
Info:        Working on 8424
Info:            Created 
Info:        Working on 8098
Info:            Created 
Info:        Working on 8262
Info:            Created 
Info:        Working on 8417
Info:            Created 
Info:        Working on 8497
Info:            Created 
Info:        Working on 8396
Info:            Created 
Info:        Working on 8097
Info:            Created 
Info:        Working on 8410
Info:            Created 
Info:        Working on 8510
Info:            Created 
Info:        Working on 8573
Info:            Created 
Info:        Working on 8577
Info:            Created 
Info:        Working on 8518
Info:            Created 
Info:        Working on 8277
Info:            Created 
Info:        Working on 8266
Info:            Created 
Info:        Working on 8499
Info:            Created 
Info:        Working on 8402
Info:            Created 
Info:        Working on 8602
Info:            Created 
Info:        Working on 8501
Info:            Created 
Info:        Working on 8612
Info:            Created 
Info:        Working on 8567
Info:            Created 
Info:        Working on 8611
Info:            Created 
Info:        Working on 8603
Info:            Created 
Info:        Working on 8599
Info:            Created 
Info:        Working on 8606
Info:            Created 
Info:        Working on 8579
Info:            Created 
Info:        Working on 8495
Info:            Created 
Info:        Working on 1740
Info:            Created 
Info:        Working on 1391
Info:            Created 
Info:        Working on 597
Info:            Created 
Info:        Working on 1100
Info:            Created 
Info:        Working on 1412
Info:            Created 
Info:        Working on 1097
Info:            Created 
Info:        Working on 1739
Info:            Created 
Info:        Working on 1738
Info:            Created 
Info:        Working on 598
Info:            Created 
Info:        Working on 826
Info:            Created 
Info:        Working on 1405
Info:            Created 
Info:        Working on 1102
Info:            Created 
Info:        Working on 1415
Info:            Created 
Info:        Working on 1402
Info:            Created 
Info:        Working on 1395
Info:            Created 
Info:        Working on 1741
Info:            Created 
Info:        Working on 814
Info:            Created 
Info:        Working on 1719
Info:            Created 
Info:        Working on 2057
Info:            Created 
Info:        Working on 1734
Info:            Created 
Info:        Working on 1396
Info:            Created 
Info:        Working on 2056
Info:            Created 
Info:        Working on 2058
Info:            Created 
Info:        Working on 808
Info:            Created 
Info:        Working on 1384
Info:            Created 
Info:        Working on 1721
Info:            Created 
Info:        Working on 1730
Info:            Created 
Info:        Working on 94
Info:            Created 
Info:        Working on 135
Info:            Created 
Info:        Working on 181
Info:            Created 
Info:        Created 
Info:    Working on BRep 0
Info:        Using 3D tolerance 1e-006
Info:        Using 3D tolerance 1e-006
Info:        Created BRep 
Info:    Finished with 
Info:    Points:                 0 found       0 created       0 failed
Info:    Coordinate Systems      0 found       0 created       0 failed
Info:    Curves:                 0 found       0 created       0 failed
Info:    Surfaces:               0 found       0 created       0 failed
Info:    Trimmed Surfaces:       0 found       0 created       0 failed
Info:    Breps:                  1 found       1 created       0 failed
Finished logging messages at Tue Mar 28 06:24:20 2017
