Started logging messages at Sun Mar 12 01:47:18 2017
Info:    Using UV tolerance 1e-006
Info:    Using UV tolerance 1e-006
Info:    HwNlibToTSLib options selected:
Info:        Points: Off
Info:        Curves: On
Info:        Surfaces: Off
Info:        BReps: On
Info:        Do not create IwAssembly/IwAssemblyInstance objects
Info:        Making untrimmed surfaces into BReps
Info:        Making solids into single BReps
Info:        Make components of failed trims
Info:        Make faces of failed B-reps
Info:    HW SAT v1.2.6-maint
Info:    Reading 
Info:    Processing 
Info:    Transferring 
Info:    
Info:    Found 0 points in file
Info:    Found 0 curves in file
Info:    Found 0 surfaces in file
Info:    Found 0 trimmed surfaces in file
Info:    Found 1 B-reps in file
Info:    Found 32 B-rep faces in file
Info:    
Info:    Using 3D tolerance 1e-006
Info:    Working on 0
Info:        Working on 60
Info:            Created 
Info:        Working on 61
Info:            Created 
Info:        Working on 80
Info:            Created 
Info:        Working on 82
Info:            Created 
Info:        Working on 6
Info:            Created 
Info:        Working on 78
Info:            Created 
Info:        Working on 106
Info:            Created 
Info:        Working on 9
Info:            Created 
Info:        Working on 104
Info:            Created 
Info:        Working on 134
Info:            Created 
Info:        Working on 13
Info:            Created 
Info:        Working on 21
Info:            Created 
Info:        Working on 173
Info:            Created 
Info:        Working on 214
Info:            Created 
Info:        Working on 183
Info:            Created 
Info:        Working on 117
Info:            Created 
Info:        Working on 38
Info:            Created 
Info:        Working on 212
Info:            Created 
Info:        Working on 203
Info:            Created 
Info:        Working on 64
Info:            Created 
Info:        Working on 94
Info:            Created 
Info:        Working on 294
Info:            Created 
Info:        Working on 245
Info:            Created 
Info:        Working on 127
Info:            Created 
Info:        Working on 164
Info:            Created 
Info:        Working on 362
Info:            Created 
Info:        Working on 284
Info:            Created 
Info:        Working on 209
Info:            Created 
Info:        Working on 249
Info:            Created 
Info:        Working on 439
Info:            Created 
Info:        Working on 313
Info:            Created 
Info:        Working on 291
Info:            Created 
Info:        Working on 326
Info:            Created 
Info:        Working on 231
Info:            Created 
Info:        Working on 265
Info:            Created 
Info:        Working on 305
Info:            Created 
Info:        Working on 332
Info:            Created 
Info:        Working on 303
Info:            Created 
Info:        Working on 195
Info:            Created 
Info:        Working on 277
Info:            Created 
Info:        Working on 271
Info:            Created 
Info:        Working on 308
Info:            Created 
Info:        Working on 306
Info:            Created 
Info:        Working on 260
Info:            Created 
Info:        Working on 330
Info:            Created 
Info:        Working on 152
Info:            Created 
Info:        Working on 239
Info:            Created 
Info:        Working on 295
Info:            Created 
Info:        Working on 221
Info:            Created 
Info:        Working on 238
Info:            Created 
Info:        Working on 422
Info:            Created 
Info:        Working on 423
Info:            Created 
Info:        Working on 453
Info:            Created 
Info:        Working on 454
Info:            Created 
Info:        Working on 280
Info:            Created 
Info:        Working on 450
Info:            Created 
Info:        Working on 470
Info:            Created 
Info:        Working on 311
Info:            Created 
Info:        Working on 468
Info:            Created 
Info:        Working on 474
Info:            Created 
Info:        Working on 336
Info:            Created 
Info:        Working on 365
Info:            Created 
Info:        Working on 402
Info:            Created 
Info:        Working on 358
Info:            Created 
Info:        Working on 359
Info:            Created 
Info:        Working on 437
Info:            Created 
Info:        Working on 438
Info:            Created 
Info:        Working on 398
Info:            Created 
Info:        Working on 391
Info:            Created 
Info:        Working on 463
Info:            Created 
Info:        Working on 435
Info:            Created 
Info:        Working on 387
Info:            Created 
Info:        Working on 461
Info:            Created 
Info:        Working on 459
Info:            Created 
Info:        Working on 430
Info:            Created 
Info:        Working on 456
Info:            Created 
Info:        Working on 91
Info:            Created 
Info:        Working on 124
Info:            Created 
Info:        Working on 160
Info:            Created 
Info:        Working on 205
Info:            Created 
Info:        Created 
Info:    Working on BRep 0
Info:        Using 3D tolerance 1e-006
Info:        Using 3D tolerance 1e-006
Info:        Created BRep 
Info:    Finished with 
Info:    Points:                 0 found       0 created       0 failed
Info:    Coordinate Systems      0 found       0 created       0 failed
Info:    Curves:                 0 found       0 created       0 failed
Info:    Surfaces:               0 found       0 created       0 failed
Info:    Trimmed Surfaces:       0 found       0 created       0 failed
Info:    Breps:                  1 found       1 created       0 failed
Finished logging messages at Sun Mar 12 01:47:18 2017
