Started logging messages at Wed Aug 31 23:07:19 2016
Info:    Using UV tolerance 1e-006
Info:    Using UV tolerance 1e-006
Info:    HwNlibToTSLib options selected:
Info:        Points: Off
Info:        Curves: On
Info:        Surfaces: Off
Info:        BReps: On
Info:        Do not create IwAssembly/IwAssemblyInstance objects
Info:        Making untrimmed surfaces into BReps
Info:        Making solids into single BReps
Info:        Make components of failed trims
Info:        Make faces of failed B-reps
Info:    HW SAT v1.2.6-maint
Info:    Reading 
Info:    Processing 
Info:    Transferring 
Info:    
Info:    Found 0 points in file
Info:    Found 0 curves in file
Info:    Found 0 surfaces in file
Info:    Found 0 trimmed surfaces in file
Info:    Found 1 B-reps in file
Info:    Found 64 B-rep faces in file
Info:    
Info:    Using 3D tolerance 1e-006
Info:    Working on 0
Info:        Working on 60
Info:            Created 
Info:        Working on 61
Info:            Created 
Info:        Working on 87
Info:            Created 
Info:        Working on 91
Info:            Created 
Info:        Working on 6
Info:            Created 
Info:        Working on 86
Info:            Created 
Info:        Working on 124
Info:            Created 
Info:        Working on 164
Info:            Created 
Info:        Working on 210
Info:            Created 
Info:        Working on 208
Info:            Created 
Info:        Working on 157
Info:            Created 
Info:        Working on 9
Info:            Created 
Info:        Working on 158
Info:            Created 
Info:        Working on 13
Info:            Created 
Info:        Working on 209
Info:            Created 
Info:        Working on 21
Info:            Created 
Info:        Working on 264
Info:            Created 
Info:        Working on 38
Info:            Created 
Info:        Working on 265
Info:            Created 
Info:        Working on 64
Info:            Created 
Info:        Working on 213
Info:            Created 
Info:        Working on 101
Info:            Created 
Info:        Working on 142
Info:            Created 
Info:        Working on 146
Info:            Created 
Info:        Working on 136
Info:            Created 
Info:        Working on 470
Info:            Created 
Info:        Working on 471
Info:            Created 
Info:        Working on 545
Info:            Created 
Info:        Working on 547
Info:            Created 
Info:        Working on 185
Info:            Created 
Info:        Working on 453
Info:            Created 
Info:        Working on 593
Info:            Created 
Info:        Working on 672
Info:            Created 
Info:        Working on 728
Info:            Created 
Info:        Working on 726
Info:            Created 
Info:        Working on 666
Info:            Created 
Info:        Working on 239
Info:            Created 
Info:        Working on 667
Info:            Created 
Info:        Working on 300
Info:            Created 
Info:        Working on 727
Info:            Created 
Info:        Working on 375
Info:            Created 
Info:        Working on 762
Info:            Created 
Info:        Working on 457
Info:            Created 
Info:        Working on 697
Info:            Created 
Info:        Working on 532
Info:            Created 
Info:        Working on 592
Info:            Created 
Info:        Working on 594
Info:            Created 
Info:        Working on 367
Info:            Created 
Info:        Working on 529
Info:            Created 
Info:        Working on 563
Info:            Created 
Info:        Working on 274
Info:            Created 
Info:        Working on 228
Info:            Created 
Info:        Working on 426
Info:            Created 
Info:        Working on 350
Info:            Created 
Info:        Working on 342
Info:            Created 
Info:        Working on 294
Info:            Created 
Info:        Working on 454
Info:            Created 
Info:        Working on 568
Info:            Created 
Info:        Working on 634
Info:            Created 
Info:        Working on 635
Info:            Created 
Info:        Working on 571
Info:            Created 
Info:        Working on 424
Info:            Created 
Info:        Working on 435
Info:            Created 
Info:        Working on 503
Info:            Created 
Info:        Working on 509
Info:            Created 
Info:        Working on 573
Info:            Created 
Info:        Working on 513
Info:            Created 
Info:        Working on 636
Info:            Created 
Info:        Working on 443
Info:            Created 
Info:        Working on 576
Info:            Created 
Info:        Working on 359
Info:            Created 
Info:        Working on 515
Info:            Created 
Info:        Working on 179
Info:            Created 
Info:        Working on 370
Info:            Created 
Info:        Working on 287
Info:            Created 
Info:        Working on 485
Info:            Created 
Info:        Working on 623
Info:            Created 
Info:        Working on 718
Info:            Created 
Info:        Working on 721
Info:            Created 
Info:        Working on 362
Info:            Created 
Info:        Working on 714
Info:            Created 
Info:        Working on 776
Info:            Created 
Info:        Working on 840
Info:            Created 
Info:        Working on 909
Info:            Created 
Info:        Working on 910
Info:            Created 
Info:        Working on 845
Info:            Created 
Info:        Working on 447
Info:            Created 
Info:        Working on 677
Info:            Created 
Info:        Working on 794
Info:            Created 
Info:        Working on 518
Info:            Created 
Info:        Working on 858
Info:            Created 
Info:        Working on 579
Info:            Created 
Info:        Working on 919
Info:            Created 
Info:        Working on 639
Info:            Created 
Info:        Working on 918
Info:            Created 
Info:        Working on 700
Info:            Created 
Info:        Working on 854
Info:            Created 
Info:        Working on 765
Info:            Created 
Info:        Working on 830
Info:            Created 
Info:        Working on 735
Info:            Created 
Info:        Working on 829
Info:            Created 
Info:        Working on 694
Info:            Created 
Info:        Working on 902
Info:            Created 
Info:        Working on 972
Info:            Created 
Info:        Working on 795
Info:            Created 
Info:        Working on 757
Info:            Created 
Info:        Working on 893
Info:            Created 
Info:        Working on 962
Info:            Created 
Info:        Working on 1019
Info:            Created 
Info:        Working on 1023
Info:            Created 
Info:        Working on 970
Info:            Created 
Info:        Working on 827
Info:            Created 
Info:        Working on 815
Info:            Created 
Info:        Working on 951
Info:            Created 
Info:        Working on 885
Info:            Created 
Info:        Working on 1057
Info:            Created 
Info:        Working on 953
Info:            Created 
Info:        Working on 1076
Info:            Created 
Info:        Working on 1013
Info:            Created 
Info:        Working on 1075
Info:            Created 
Info:        Working on 1058
Info:            Created 
Info:        Working on 1054
Info:            Created 
Info:        Working on 1061
Info:            Created 
Info:        Working on 1025
Info:            Created 
Info:        Working on 949
Info:            Created 
Info:        Working on 742
Info:            Created 
Info:        Working on 916
Info:            Created 
Info:        Working on 935
Info:            Created 
Info:        Working on 855
Info:            Created 
Info:        Working on 490
Info:            Created 
Info:        Working on 473
Info:            Created 
Info:        Working on 397
Info:            Created 
Info:        Working on 329
Info:            Created 
Info:        Working on 552
Info:            Created 
Info:        Working on 939
Info:            Created 
Info:        Working on 942
Info:            Created 
Info:        Working on 621
Info:            Created 
Info:        Working on 992
Info:            Created 
Info:        Working on 1040
Info:            Created 
Info:        Working on 1069
Info:            Created 
Info:        Working on 1070
Info:            Created 
Info:        Working on 1045
Info:            Created 
Info:        Working on 680
Info:            Created 
Info:        Working on 1029
Info:            Created 
Info:        Working on 738
Info:            Created 
Info:        Working on 1064
Info:            Created 
Info:        Working on 798
Info:            Created 
Info:        Working on 1077
Info:            Created 
Info:        Working on 861
Info:            Created 
Info:        Working on 1073
Info:            Created 
Info:        Working on 922
Info:            Created 
Info:        Working on 1049
Info:            Created 
Info:        Working on 981
Info:            Created 
Info:        Working on 1030
Info:            Created 
Info:        Working on 978
Info:            Created 
Info:        Working on 483
Info:            Created 
Info:        Working on 198
Info:            Created 
Info:        Working on 327
Info:            Created 
Info:        Working on 406
Info:            Created 
Info:        Working on 403
Info:            Created 
Info:        Working on 554
Info:            Created 
Info:        Working on 482
Info:            Created 
Info:        Working on 387
Info:            Created 
Info:        Working on 235
Info:            Created 
Info:        Working on 297
Info:            Created 
Info:        Working on 372
Info:            Created 
Info:        Working on 250
Info:            Created 
Info:        Working on 312
Info:            Created 
Info:        Working on 98
Info:            Created 
Info:        Working on 145
Info:            Created 
Info:        Working on 201
Info:            Created 
Info:        Working on 260
Info:            Created 
Info:        Created 
Info:    Working on BRep 0
Info:        Using 3D tolerance 1e-006
Info:        Using 3D tolerance 1e-006
Info:        Created BRep 
Info:    Finished with 
Info:    Points:                 0 found       0 created       0 failed
Info:    Coordinate Systems      0 found       0 created       0 failed
Info:    Curves:                 0 found       0 created       0 failed
Info:    Surfaces:               0 found       0 created       0 failed
Info:    Trimmed Surfaces:       0 found       0 created       0 failed
Info:    Breps:                  1 found       1 created       0 failed
Finished logging messages at Wed Aug 31 23:07:19 2016
